{ 
  "text" : "An issue was discovered in py-lmdb 0.97. For certain values of mn_flags, mdb_cursor_set triggers a memcpy with an invalid write operation within mdb_xcursor_init1. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "Campaign#d8f9a5bafc665e05905f35e6408e2c7e" ,
    "type" : "Campaign" ,
    "subType" : "Campaign" ,
    "value" : "invalid write operation" ,
    "begin" : 114 ,
    "end" : 137 ,
    "canonicalForm" : "invalid write operation" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "FileName#8192d4110ea5d0e0f71a155d4100eafc" ,
    "type" : "FileName" ,
    "subType" : "FileName" ,
    "value" : "data.mdb" ,
    "begin" : 207 ,
    "end" : 215 ,
    "canonicalForm" : "data.mdb" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "3f858cf8cfd59f25010e71b6b5671428" ,
    "type" : "MiscEntity" ,
    "subType" : "attacker" ,
    "value" : "attacker" ,
    "begin" : 236 ,
    "end" : 244 ,
    "canonicalForm" : "attacker" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "supplied_by" ,
    "predicate" : { 
      "begin" : 221 ,
      "end" : 232 ,
      "surfaceForm" : "supplied by"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 207 ,
      "end" : 215 ,
      "eid" : "E2" ,
      "canonicalForm" : "data.mdb"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 236 ,
      "end" : 244 ,
      "eid" : "E3" ,
      "canonicalForm" : "attacker"
    }
    ,  ]
  }
  ,  ]
}
