{ 
  "text" : "Multiple integer overflows in audioop.c in the audioop module in Python 2.6, 2.7, 3.1, and 3.2 allow context-dependent attackers to cause a denial of service (application crash) via a large fragment, as demonstrated by a call to audioop.lin2lin with a long string in the first argument, leading to a buffer overflow.  NOTE: this vulnerability exists because of an incorrect fix for CVE-2008-3143.5.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 140 ,
    "end" : 157 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "Vulnerability#4ce61ca473e0a8f2fdbb857a0a53b5bc" ,
    "type" : "Vulnerability" ,
    "subType" : "Vulnerability" ,
    "value" : "buffer overflow" ,
    "begin" : 300 ,
    "end" : 315 ,
    "canonicalForm" : "buffer overflow" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "Vulnerability#31d778034703fc8b706856daa19bbf79" ,
    "type" : "Vulnerability" ,
    "subType" : "CVE" ,
    "value" : "cve-2008-3143" ,
    "begin" : 382 ,
    "end" : 395 ,
    "canonicalForm" : "CVE-2008-3143" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 140 ,
      "end" : 157 ,
      "eid" : "E1" ,
      "canonicalForm" : "denial of service"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 300 ,
      "end" : 315 ,
      "eid" : "E2" ,
      "canonicalForm" : "buffer overflow"
    }
    ,  ]
  }
  ,  ]
}
