{ 
  "text" : "Xen 3.4, 4.0, and 4.1, when the guest OS has not registered a handler for a syscall or sysenter instruction, does not properly clear a flag for exception injection when injecting a General Protection Fault, which allows local PV guest OS users to cause a denial of service (guest crash) by later triggering an exception that would normally be handled within Xen.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "Identity#b05364c0b6adeed8cb79e3c3e9a6e5ee" ,
    "type" : "Identity" ,
    "subType" : "Organization" ,
    "value" : "xen" ,
    "begin" : 0 ,
    "end" : 3 ,
    "canonicalForm" : "Xen" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 255 ,
    "end" : 272 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "Identity#b05364c0b6adeed8cb79e3c3e9a6e5ee" ,
    "type" : "Identity" ,
    "subType" : "Organization" ,
    "value" : "xen" ,
    "begin" : 358 ,
    "end" : 361 ,
    "canonicalForm" : "Xen" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 0 ,
      "end" : 3 ,
      "eid" : "E1" ,
      "canonicalForm" : "Xen"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 255 ,
      "end" : 272 ,
      "eid" : "E2" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R2" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 255 ,
      "end" : 272 ,
      "eid" : "E2" ,
      "canonicalForm" : "denial of service"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 358 ,
      "end" : 361 ,
      "eid" : "E3" ,
      "canonicalForm" : "Xen"
    }
    ,  ]
  }
  ,  ]
}
