{ 
  "text" : "The validate_as_request function in kdc_util.c in the Key Distribution Center (KDC) in MIT Kerberos 5 (aka krb5) before 1.13.6 and 1.4.x before 1.14.3, when restrict_anonymous_to_tgt is enabled, uses an incorrect client data structure, which allows remote authenticated users to cause a denial of service (NULL pointer dereference and daemon crash) via an S4U2Self request.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "179709c1d52b2d82c3486108850b32c6" ,
    "type" : "MiscEntity" ,
    "subType" : "user" ,
    "value" : "remote authenticated user" ,
    "begin" : 249 ,
    "end" : 275 ,
    "canonicalForm" : "remote authenticated user" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 287 ,
    "end" : 304 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "cause" ,
    "predicate" : { 
      "begin" : 276 ,
      "end" : 284 ,
      "surfaceForm" : "to cause"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 249 ,
      "end" : 275 ,
      "eid" : "E1" ,
      "canonicalForm" : "remote authenticated user"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 287 ,
      "end" : 304 ,
      "eid" : "E2" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  ,  ]
}
