{ 
  "text" : "An issue was discovered in the Linux kernel through 4.17.10. There is an out-of-bounds access in __remove_dirty_segment() in fs/f2fs/segment.c when mounting an f2fs image.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "0aae4c8f3cc35693d0cbbe631f2e8b52" ,
    "type" : "MiscEntity" ,
    "subType" : "issue" ,
    "value" : "issue" ,
    "begin" : 3 ,
    "end" : 8 ,
    "canonicalForm" : "issue" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "Identity#e206a54e97690cce50cc872dd70ee896" ,
    "type" : "Identity" ,
    "subType" : "Organization" ,
    "value" : "linux" ,
    "begin" : 31 ,
    "end" : 36 ,
    "canonicalForm" : "Linux" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "Product#e206a54e97690cce50cc872dd70ee896" ,
    "type" : "Product" ,
    "subType" : "OperatingSystem" ,
    "value" : "linux" ,
    "begin" : 31 ,
    "end" : 36 ,
    "canonicalForm" : "Linux" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E4" ,
    "keyid" : "FilePath#c06e31c9081078ffb714e21cec36f157" ,
    "type" : "FilePath" ,
    "subType" : "FilePath" ,
    "value" : "/f2fs/segment" ,
    "begin" : 127 ,
    "end" : 140 ,
    "canonicalForm" : "/f2fs/segment" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "discovered_in" ,
    "predicate" : { 
      "begin" : 13 ,
      "end" : 26 ,
      "surfaceForm" : "discovered in"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 3 ,
      "end" : 8 ,
      "eid" : "E1" ,
      "canonicalForm" : "issue"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 31 ,
      "end" : 36 ,
      "eid" : "E2" ,
      "canonicalForm" : "Linux"
    }
    ,  ]
  }
  ,  ]
}
