{ 
  "text" : "An issue was discovered in drivers/scsi/qedi/qedi_dbg.c in the Linux kernel before 5.1.12. In the qedi_dbg_* family of functions, there is an out-of-bounds read.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "FilePath#5ab61015dfed58ce02091930fcadfc6a" ,
    "type" : "FilePath" ,
    "subType" : "FilePath" ,
    "value" : "/scsi/qedi/qedi_dbg" ,
    "begin" : 34 ,
    "end" : 53 ,
    "canonicalForm" : "/scsi/qedi/qedi_dbg" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "Identity#e206a54e97690cce50cc872dd70ee896" ,
    "type" : "Identity" ,
    "subType" : "Organization" ,
    "value" : "linux" ,
    "begin" : 63 ,
    "end" : 68 ,
    "canonicalForm" : "Linux" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "Product#e206a54e97690cce50cc872dd70ee896" ,
    "type" : "Product" ,
    "subType" : "OperatingSystem" ,
    "value" : "linux" ,
    "begin" : 63 ,
    "end" : 68 ,
    "canonicalForm" : "Linux" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 34 ,
      "end" : 53 ,
      "eid" : "E1" ,
      "canonicalForm" : "/scsi/qedi/qedi_dbg"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 63 ,
      "end" : 68 ,
      "eid" : "E2" ,
      "canonicalForm" : "Linux"
    }
    ,  ]
  }
  , { 
    "rid" : "R2" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 34 ,
      "end" : 53 ,
      "eid" : "E1" ,
      "canonicalForm" : "/scsi/qedi/qedi_dbg"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 63 ,
      "end" : 68 ,
      "eid" : "E3" ,
      "canonicalForm" : "Linux"
    }
    ,  ]
  }
  ,  ]
}
