{ 
  "text" : "UltraVNC revision 1210 has out-of-bounds read vulnerability in VNC client code inside Ultra decoder, which results in a denial of service (DoS) condition. This attack appear to be exploitable via network connectivity. This vulnerability has been fixed in revision 1211.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "Identity#8ad050201cfb574cef6efc69ff2ade08" ,
    "type" : "Identity" ,
    "subType" : "Organization" ,
    "value" : "ultravnc" ,
    "begin" : 0 ,
    "end" : 8 ,
    "canonicalForm" : "UltraVNC" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "Vulnerability#94ac1b061609f08a32b1b5e94c114ff9" ,
    "type" : "Vulnerability" ,
    "subType" : "Vulnerability" ,
    "value" : "bounds read vulnerability" ,
    "begin" : 34 ,
    "end" : 59 ,
    "canonicalForm" : "bounds read vulnerability" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 120 ,
    "end" : 137 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E4" ,
    "keyid" : "Product#0196f6c4f97df3f48d570c23e46501ae" ,
    "type" : "Product" ,
    "subType" : "OperatingSystem" ,
    "value" : "dos" ,
    "begin" : 139 ,
    "end" : 142 ,
    "canonicalForm" : "DoS" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [  ]
}
