{ 
  "text" : "An issue was discovered in the Linux kernel before 4.19.9. The USB subsystem mishandles size checks during the reading of an extra descriptor, related to __usb_get_extra_descriptor in drivers/usb/core/usb.c.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "0aae4c8f3cc35693d0cbbe631f2e8b52" ,
    "type" : "MiscEntity" ,
    "subType" : "issue" ,
    "value" : "issue" ,
    "begin" : 3 ,
    "end" : 8 ,
    "canonicalForm" : "issue" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "Identity#e206a54e97690cce50cc872dd70ee896" ,
    "type" : "Identity" ,
    "subType" : "Organization" ,
    "value" : "linux" ,
    "begin" : 31 ,
    "end" : 36 ,
    "canonicalForm" : "Linux" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "Product#e206a54e97690cce50cc872dd70ee896" ,
    "type" : "Product" ,
    "subType" : "OperatingSystem" ,
    "value" : "linux" ,
    "begin" : 31 ,
    "end" : 36 ,
    "canonicalForm" : "Linux" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E4" ,
    "keyid" : "FilePath#f658e41276188dcb6f09e19f352b2fde" ,
    "type" : "FilePath" ,
    "subType" : "FilePath" ,
    "value" : "/usb/core/usb" ,
    "begin" : 191 ,
    "end" : 204 ,
    "canonicalForm" : "/usb/core/usb" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "discovered_in" ,
    "predicate" : { 
      "begin" : 13 ,
      "end" : 26 ,
      "surfaceForm" : "discovered in"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 3 ,
      "end" : 8 ,
      "eid" : "E1" ,
      "canonicalForm" : "issue"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 31 ,
      "end" : 36 ,
      "eid" : "E2" ,
      "canonicalForm" : "Linux"
    }
    ,  ]
  }
  ,  ]
}
