{ 
  "text" : "An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node->mn_hi, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "Campaign#d8f9a5bafc665e05905f35e6408e2c7e" ,
    "type" : "Campaign" ,
    "subType" : "Campaign" ,
    "value" : "invalid write operation" ,
    "begin" : 138 ,
    "end" : 161 ,
    "canonicalForm" : "invalid write operation" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "FileName#8192d4110ea5d0e0f71a155d4100eafc" ,
    "type" : "FileName" ,
    "subType" : "FileName" ,
    "value" : "data.mdb" ,
    "begin" : 206 ,
    "end" : 214 ,
    "canonicalForm" : "data.mdb" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "3f858cf8cfd59f25010e71b6b5671428" ,
    "type" : "MiscEntity" ,
    "subType" : "attacker" ,
    "value" : "attacker" ,
    "begin" : 235 ,
    "end" : 243 ,
    "canonicalForm" : "attacker" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "supplied_by" ,
    "predicate" : { 
      "begin" : 220 ,
      "end" : 231 ,
      "surfaceForm" : "supplied by"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 206 ,
      "end" : 214 ,
      "eid" : "E2" ,
      "canonicalForm" : "data.mdb"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 235 ,
      "end" : 243 ,
      "eid" : "E3" ,
      "canonicalForm" : "attacker"
    }
    ,  ]
  }
  ,  ]
}
